networks:
  mcp-networks:
    driver: bridge

services:
  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  # db:
  #   container_name: mcp-database
  #   image: postgres:13
  #   volumes:
  #     - db_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - mcp-networks
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  mcp-financial:
    build:
      context: .
      dockerfile: mcp-financial/Dockerfile
    container_name: mcp_financial
    environment:
      - MCP_SERVER_NAME=FinancialHistoryServer
    ports:
      - "8001:8000"
    depends_on:
      - redis
    networks:
      - mcp-networks

  mcp-stock:
    build:
      context: .
      dockerfile: mcp-stock/Dockerfile
    container_name: mcp_stock
    environment:
      - MCP_SERVER_NAME=LiveStockServer
    ports:
      - "8002:8000"
    depends_on:
      - redis

  mcp-docs:
    build:
      context: .
      dockerfile: mcp-docs/Dockerfile
    container_name: mcp_docs
    environment:
      - MCP_SERVER_NAME=DocumentSearchServer
    ports:
      - "8003:8000"
    depends_on:
      - redis

volumes:
  db_data: